@startuml Бронирование в хостеле

start

:Гость заходит на сайт;
:Выбирает даты заезда и выезда;
:Просматривает свободные комнаты;

if (Есть свободные комнаты?) then (да)
  :Выбирает комнату;
  :Заполняет данные;
  
  if (Данные корректны?) then (да)
    :Оформляет бронирование;
    
    if (Оплата сразу?) then (да)
      :Оплачивает онлайн;
      :Получает подтверждение на email;
    else (нет)
      :Бронь без оплаты;
      :Получает номер брони;
    endif
    
    :Администратор получает уведомление;
    :Администратор подтверждает бронь;
    :Гость приезжает в хостел;
    :Администратор регистрирует гостя;
    :Выдает ключи от комнаты;
    :Гость заселяется;
    
    stop
    
  else (нет)
    :Показывает ошибки в форме;
    stop
  endif
  
else (нет)
  :Показывает сообщение "Нет свободных мест";
  :Предлагает изменить даты;
  stop
endif

@enduml
